In [1]:
import pandas as pd
import numpy as np

top100 = pd.read_csv('./data/읍면동별_자전거_총대여반납건수_상위100개_서울.csv',encoding='cp949')
top50 = pd.read_csv('./data/읍면동별_자전거_총대여반납건수_상위50개_서울.csv',encoding='cp949') #csv 파일 불러옴

In [2]:
school = pd.read_csv('./data/읍면동별_학교_서울.csv',encoding='cp949') #행정동별 학교 개수 추출
school["학교개수"] = ""
school = school.groupby('행정동명').학교개수.count().to_frame()

movie = pd.read_csv('./data/읍면동별_영화관_서울.csv',encoding='cp949') #행정동별 영화관 개수 추출
movie["영화관개수"] = ""
movie = movie.groupby('행정동명').영화관개수.count().to_frame()

university = pd.read_csv('./data/읍면동별_대학교_서울.csv',encoding='cp949') #행정동별 대학교 개수 추출
university["대학교개수"] = ""
university = university.groupby('행정동명').대학교개수.count().to_frame()

In [3]:
#변수 csv파일 불러오기
facility = pd.read_csv('./data/읍면동별_시설물수_서울.csv',encoding='cp949')
populationDensity = pd.read_csv('./data/읍면동별_인구밀도및인구수_서울.csv',encoding='UTF8')
river = pd.read_csv('./data/읍면동별_인접한강_서울.csv',encoding='cp949')
stream = pd.read_csv('./data/읍면동별_인접한하천_서울.csv',encoding='cp949')
car = pd.read_csv('./data/읍면동별_자동차등록대수_서울.csv',encoding='cp949')
byciclePath = pd.read_csv('./data/읍면동별_자전거도로_서울.csv',encoding='cp949')
subway = pd.read_csv('./data/읍면동별_지하철승객수_서울.csv',encoding='UTF8')
bus = pd.read_csv('./data/읍면동별_버스승객수_서울.csv',encoding='UTF8')

## 읍면동별_자전거_총대여반납건수_상위100개_서울

In [4]:
#변수 join
data100=pd.merge(left = top100,right = facility,on='행정동_코드',how="left")
data100=pd.merge(left = data100,right = populationDensity,on="행정동명",how="left")
data100=pd.merge(left = data100, right = river,on="행정동명",how="left")
data100=pd.merge(left = data100, right = stream,on="행정동명",how="left")
data100=pd.merge(left = data100, right = car,on="행정동명",how="left")
data100=pd.merge(left = data100, right = byciclePath,on="행정동명",how="left")
data100=pd.merge(left = data100, right = subway,on='행정동_코드',how="left")
data100=pd.merge(left = data100, right = bus,on='행정동_코드',how="left")
data100=pd.merge(left = data100, right = school,on='행정동명',how="left")
data100=pd.merge(left = data100, right = movie,on='행정동명',how="left")
data100=pd.merge(left = data100, right = university,on='행정동명',how="left")

In [5]:
#중복행 삭제
data100.drop_duplicates()

,행정동명,행정동_코드,총반납대여,cluster,시설물개수,구,인구 (명),면적 (㎢),인구밀도 (명/㎢),강,하천,자동차등록대수,자전거도로(km),지하철_총승객수,버스_총승객수,학교개수,영화관개수,대학교개수
0,가산동,11545510,70811,1,17,금천구,26569,2.52,10543,NaN,안양천,8485.000000,0.920000,7204395.0,1765497,NaN,2.0,NaN
1,가양1동,11500603,303516,2,20,강서구,34359,4.70,7310,NaN,NaN,9477.400000,3.855000,522372.0,711582,2.0,1.0,NaN
2,가양2동,11500604,31106,3,11,강서구,13902,1.00,13902,한강,NaN,9477.400000,3.855000,NaN,112027,3.0,NaN,NaN
3,강일동,11740515,44041,2,10,강동구,33057,2.26,14627,NaN,NaN,7995.555556,4.133333,NaN,545602,5.0,NaN,NaN
4,공릉1동,11350595,41953,2,14,노원구,37184,1.41,26372,NaN,중랑천,7550.157895,2.300000,1680496.0,607633,7.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,혜화동,11110650,32034,0,8,종로구,19392,1.12,17314,NaN,NaN,2607.352941,1.888235,2014877.0,976690,7.0,1.0,NaN
96,화곡1동,11500540,31854,2,21,강서구,52647,1.12,47006,NaN,NaN,9477.400000,3.855000,4586661.0,1088378,3.0,1.0,NaN
97,화곡6동,11500591,30528,0,6,강서구,25303,1.11,22795,NaN,NaN,9477.400000,3.855000,NaN,766801,1.0,NaN,NaN
98,화양동,11215710,75248,0,10,광진구,27082,1.16,23347,NaN,NaN,6175.666667,3.220000,5812056.0,656642,3.0,1.0,1.0
99,휘경2동,11230730,29662,0,6,동대문구,24666,1.05,23491,NaN,중랑천,6721.000000,2.692857,NaN,663715,11.0,NaN,1.0

In [12]:
data100.to_csv('./data/seoul_data100.csv',index=False)

## 읍면동별_자전거_총대여반납건수_상위50개_서울

In [13]:
data50=pd.merge(left = top50,right = facility,on='행정동_코드',how="left")
data50=pd.merge(left = data50,right = populationDensity,on="행정동명",how="left")
data50=pd.merge(left = data50, right = river,on="행정동명",how="left")
data50=pd.merge(left = data50, right = stream,on="행정동명",how="left")
data50=pd.merge(left = data50, right = car,on="행정동명",how="left")
data50=pd.merge(left = data50, right = byciclePath,on="행정동명",how="left")
data50=pd.merge(left = data50, right = subway,on='행정동_코드',how="left")
data50=pd.merge(left = data50, right = bus,on='행정동_코드',how="left")
data50=pd.merge(left = data50, right = school,on='행정동명',how="left")
data50=pd.merge(left = data50, right = movie,on='행정동명',how="left")
data50=pd.merge(left = data50, right = university,on='행정동명',how="left")

In [14]:
data50.drop_duplicates()

,행정동명,행정동_코드,총반납대여,시설물개수,구,인구 (명),면적 (㎢),인구밀도 (명/㎢),강,하천,자동차등록대수,자전거도로(km),지하철_총승객수,버스_총승객수,학교개수,영화관개수,대학교개수
0,가양1동,11500603,303516,20,강서구,34359,4.70,7310,NaN,NaN,9477.400000,3.855000,522372.0,711582,2.0,1.0,NaN
1,여의동,11560540,212352,20,영등포구,32923,8.40,3919,한강,NaN,7557.388889,3.511111,7984912.0,2788411,5.0,1.0,NaN
2,발산1동,11500611,152208,32,강서구,36236,2.94,12325,NaN,NaN,9477.400000,3.855000,1919704.0,744341,17.0,NaN,NaN
3,당산2동,11560560,109285,8,영등포구,37102,1.55,23937,한강,NaN,7557.388889,3.511111,4249030.0,1017536,7.0,NaN,NaN
4,종로1.2.3.4가동,11110615,99611,29,종로구,8700,2.35,3702,NaN,NaN,2607.352941,1.888235,11550312.0,3700523,2.0,4.0,5.0
5,상암동,11440740,99519,19,마포구,30837,8.40,3671,한강,NaN,7102.937500,4.212500,4981827.0,1616294,2.0,1.0,NaN
6,공항동,11500620,95984,9,강서구,30927,10.87,2845,NaN,NaN,9477.400000,3.855000,1073562.0,451834,6.0,NaN,NaN
7,영등포동,11560535,92540,28,영등포구,30461,1.26,24175,NaN,NaN,7557.388889,3.511111,575286.0,2147150,2.0,1.0,1.0
8,잠실6동,11710710,89795,17,송파구,16713,2.79,5990,한강,NaN,8714.740741,3.611111,766020.0,852829,3.0,1.0,NaN
9,목1동,11470510,89424,15,양천구,30536,1.41,21657,NaN,안양천,7935.166667,3.138889,944886.0,1182139,1.0,2.0,NaN
10,방화1동,11500630,83634,21,강서구,42851,1.48,28953,NaN,NaN,9477.400000,3.855000,371644.0,273859,9.0,NaN,NaN
11,오륜동,11710566,82645,5,송파구,17804,3.17,5616,NaN,NaN,8714.740741,3.611111,207869.0,380253,2.0,NaN,NaN
12,서교동,11440660,82405,26,마포구,26674,1.65,16166,NaN,NaN,7102.937500,4.212500,13594053.0,3007005,1.0,2.0,NaN
13,문래동,11560605,78292,16,영등포구,32540,1.49,21839,NaN,NaN,7557.388889,3.511111,1155598.0,717718,3.0,NaN,NaN
14,문정2동,11710642,76600,21,송파구,28841,2.20,13110,NaN,탄천,8714.740741,3.611111,2935202.0,485584,1.0,2.0,NaN
15,화양동,11215710,75248,10,광진구,27082,1.16,23347,NaN,NaN,6175.666667,3.220000,5812056.0,656642,3.0,1.0,1.0
16,자양1동,11215820,75235,7,광진구,22709,0.57,39840,NaN,NaN,6175.666667,3.220000,NaN,389865,1.0,NaN,NaN
17,잠실3동,11710680,74237,7,송파구,34143,1.49,22915,NaN,NaN,8714.740741,3.611111,NaN,1011002,3.0,NaN,NaN
18,목5동,11470550,71200,14,양천구,40737,1.81,22507,NaN,안양천,7935.166667,3.138889,218869.0,817466,8.0,NaN,NaN
19,가산동,11545510,70811,17,금천구,26569,2.52,10543,NaN,안양천,8485.000000,0.920000,7204395.0,1765497,NaN,2.0,NaN
20,성산2동,11440730,68259,16,마포구,39500,2.07,19082,NaN,홍제천,7102.937500,4.212500,746168.0,691270,8.0,2.0,NaN
21,용신동,11230536,67844,19,동대문구,36137,1.61,22445,NaN,NaN,6721.000000,2.692857,4179549.0,2056816,5.0,NaN,NaN
22,우장산동,11500615,66811,18,강서구,42883,1.36,31532,NaN,NaN,9477.400000,3.855000,NaN,600892,1.0,NaN,NaN
23,구로5동,11530560,65407,17,구로구,31740,1.03,30816,NaN,NaN,8266.125000,1.718750,6818463.0,902648,4.0,2.0,NaN
24,군자동,11215730,64366,6,광진구,21524,0.74,29086,NaN,중랑천,6175.666667,3.220000,1380098.0,536797,NaN,1.0,1.0
25,신정6동,11470670,60871,11,양천구,24152,0.96,25158,NaN,NaN,7935.166667,3.138889,385287.0,300514,5.0,NaN,NaN
26,신도림동,11530510,56318,10,구로구,36138,1.47,24584,NaN,안양천,8266.125000,1.718750,72318.0,997539,5.0,1.0,NaN
27,신정3동,11470640,55617,14,양천구,50587,2.72,18598,NaN,NaN,7935.166667,3.138889,573959.0,966712,11.0,NaN,NaN
28,자양3동,11215840,55482,7,광진구,27858,1.20,23215,한강,NaN,6175.666667,3.220000,646740.0,334923,2.0,1.0,NaN
29,구로3동,11530540,55353,9,구로구,25055,1.02,24564,NaN,NaN,8266.125000,1.718750,3914118.0,872654,3.0,NaN,NaN
30,성수1가1동,11200650,55015,3,성동구,16407,1.97,8328,한강,중랑천,5518.294118,1.635294,690144.0,283005,1.0,1.0,NaN
31,한강로동,11170625,54153,14,용산구,22886,2.90,7892,한강,NaN,4553.750000,2.031250,6963977.0,1610947,3.0,2.0,NaN
32,길동,11740685,53681,16,강동구,45374,2.17,20910,NaN,NaN,7995.555556,4.133333,445294.0,536472,12.0,NaN,NaN
33,등촌1동,11500520,53451,12,강서구,24991,0.64,39048,NaN,NaN,9477.400000,3.855000,384443.0,490017,1.0,1.0,NaN
34,독산1동,11545610,52346,30,금천구,47573,2.09,22762,NaN,안양천,8485.000000,0.920000,NaN,1199502,7.0,1.0,NaN
35,잠실2동,11710670,52243,5,송파구,34876,2.18,15998,한강,NaN,8714.740741,3.611111,1227186.0,321933,9.0,NaN,NaN
36,망원2동,11440700,50912,4,마포구,18449,0.67,27536,한강,홍제천,7102.937500,4.212500,NaN,307492,2.0,NaN,NaN
37,명동,11140550,50451,18,중구,3638,0.99,3675,NaN,NaN,3542.800000,1.493333,3618220.0,1471245,3.0,1.0,NaN
38,상계1동,11350630,49661,10,노원구,37857,5.62,6736,NaN,중랑천,7550.157895,2.300000,711969.0,436935,4.0,NaN,NaN
39,양평2동,11560620,49521,4,영등포구,22583,3.00,7528,한강,안양천,7557.388889,3.511111,437948.0,582218,3.0,NaN,NaN
40,양평1동,11560610,48913,3,영등포구,18704,0.88,21255,NaN,안양천,7557.388889,3.511111,577719.0,309118,1.0,NaN,NaN
41,신정7동,11470680,48527,7,양천구,28579,1.21,23619,NaN,안양천,7935.166667,3.138889,385287.0,242359,4.0,NaN,NaN
42,사직동,11110530,48410,17,종로구,9355,1.23,7606,NaN,NaN,2607.352941,1.888235,NaN,1464686,3.0,NaN,NaN
43,진관동,11380690,46255,19,은평구,55034,11.53,4773,NaN,NaN,7938.562500,2.793750,1163598.0,1313228,17.0,1.0,NaN
44,위례동,11710647,45347,6,송파구,44613,2.55,17495,NaN,NaN,8714.740741,3.611111,NaN,783823,6.0,NaN,NaN
45,중계1동,11350621,45260,5,노원구,26580,0.63,42190,NaN,NaN,7550.157895,2.300000,NaN,392062,4.0,NaN,NaN
46,천호2동,11740610,45047,23,강동구,33825,1.57,21545,한강,NaN,7995.555556,4.133333,NaN,547707,3.0,NaN,1.0
47,응암1동,11380580,44391,9,은평구,33279,1.20,27733,NaN,NaN,7938.562500,2.793750,1766865.0,886598,2.0,NaN,NaN
48,강일동,11740515,44041,10,강동구,33057,2.26,14627,NaN,NaN,7995.555556,4.133333,NaN,545602,5.0,NaN,NaN
49,성수2가3동,11200690,42814,8,성동구,10520,1.03,10214,NaN,중랑천,5518.294118,1.635294,2030197.0,316898,4.0,NaN,NaN

In [15]:
data50.to_csv('./data/seoul_data50.csv',index=False)